language: cpp

matrix:
  include:
    - os: linux
      compiler:
      - gcc
      - clang

    - os: osx
      compiler:
      - clang

script:
  - mkdir build
  - cd build
  - cmake ../
  - make all
  - ./travis_test
