language: cpp

git:
  depth: 5

matrix:
  include:
    - os: linux
      compiler:
      - gcc
      - clang

    - os: osx
      compiler:
      - clang

script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_CXX_STANDARD=11 -DCMAKE_BUILD_TYPE=Release
  - make all
  - ./travis_test
