language: cpp

git:
  depth: 5

jobs:
  include:
    - os: linux
      compiler: gcc
      env: CXX_STANDARD=98

    - os: linux
      compiler: gcc
      env: CXX_STANDARD=11

    - os: linux
      compiler: gcc
      env: CXX_STANDARD=14

    - os: linux
      compiler: clang
      env: CXX_STANDARD=14

    - os: osx
      compiler: clang
      env: CXX_STANDARD=14

script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DCMAKE_BUILD_TYPE=Release
  - make all
  - ./travis_test
