language: cpp

git:
  depth: 5

jobs:
  include:

    # linux - gcc
    - name: linux-gcc-98
      os: linux
      compiler: gcc
      env: CXX_STANDARD=98

    - name: linux-gcc-11
      os: linux
      compiler: gcc
      env: CXX_STANDARD=11

    - name: linux-gcc-14
      os: linux
      compiler: gcc
      env: CXX_STANDARD=14

    - name: linux-gcc-17
      os: linux
      compiler: gcc
      env: CXX_STANDARD=17

    # linux - clang
    - name: linux-clang-98
      os: linux
      compiler: clang
      env: CXX_STANDARD=98

    - name: linux-clang-11
      os: linux
      compiler: clang
      env: CXX_STANDARD=11

    - name: linux-clang-14
      os: linux
      compiler: clang
      env: CXX_STANDARD=14

    - name: linux-clang-17
      os: linux
      compiler: clang
      env: CXX_STANDARD=17

    # osx
    - name: osx-clang-14
      os: osx
      compiler: clang
      env: CXX_STANDARD=14

    # windows
    - name: windows-14
      os: windows
      env: CXX_STANDARD=14

script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DCMAKE_BUILD_TYPE=Release
  - make all
  - ./travis_test
